### ISSUE TITLE
#25add notification function to notify HoDs about edit of allocation

### ISSUE THREAD

**Issue by yylocky** [yylocky/CITS5206-Group3#25]

**Comment by kylelhk** [comment]
In response to client's clarification on 23 Aug 2023 that only HoS and HoDs can edit allocation detail:

The notification should instead be about any new comment submitted by staff regarding work allocation (e.g request for edit, comment on assignment).

**Comment by kylelhk** [comment]
Per team discussion on 7 Sep 2023 after the client meeting, a comment history page can be created for HoDs to review comments; and a pop-up notification section should be added into the navigation bar.
